name: Build Client and Server

on: [push, workflow_dispatch]

jobs:
  build:
    name: Build    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    environment: production

    permissions:
      contents: "read"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"

      - run: python3 -m pip install setuptools wheel

      - run: python3 -m pip install -r requirements.txt
      
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: client/client.py
          mode: onefile

      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: server/server.py
          mode: onefile

          
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
